from enum import Enum

# class syntax
class Commands(Enum):
    CONF= "CONF"
    SET_CONF= "SET_CONF"
    MOVE= "MOVE"
    MOVE_DONE= "MOVE_DONE"
    PROCESSING= "PROCESSING"
    PROCESSING_DONE= "PROCESSING_DONE"
    MIX_STARTED= "MIX_STARTED"
    MIX_ENDED= "MIX_ENDED"
    ORDER_UPDATED= "ORDER_UPDATED"
    MOVE_SHUTTLE_TO= "MOVE_SHUTTLE_TO"
    SET_SHUTTLE_MIX= "SET_SHUTTLE_MIX"
    MOVE_SHUTTLE_DIR= "MOVE_SHUTTLE_DIR"
    FAILED= "FAILED"